baseURL = "https://authentichibachi.com/"
title = "Authentic Hibachi"
theme = "PaperMod"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Book Online"
url = "/book-online/"
weight = 2

[[menu.main]]
name = "Gallery"
url = "/gallery/"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params.label]
text = "Authentic Hibachi"
icon = "/images/logo.jpg"
iconHeight = 60

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"